[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = "60s"
restartPolicyType = "ON_FAILURE"
numReplicas = 1

[service]
internal_port = 3000